### ISSUE TITLE
能否提供一个 packages 目录下的extjs

### ISSUE THREAD

**Issue by ibmsoft** [tengge1/ExtApp#3]
目前代码中的 index.html 页面，在 packages 目录下的extjs 没有提供，能提供一个吗，如果涉及版权不方便，可以给个文档，怎么配置用，我用下载的 6.2.1的 zip 文件，程序跑不起来，主要是文件和名称和路径和代码里的不一致

**Comment by tengge1** [comment]
现在在ExtApp/ExtApp.Web/packages目录下面有extjs。

**Comment by tengge1** [comment]
我中途更换过extjs的目录，中间有几次提交没把ExtApp/ExtApp.Web/packages提交上去，你可以下载最新的版本试一下。

**Comment by ibmsoft** [comment]
已经有了，谢谢

**Comment by tengge1** [comment]
不用谢
