### ISSUE TITLE
表单提交，显示后台校验错误

### ISSUE THREAD

**Issue by ibmsoft** [tengge1/ExtApp#4]
目前数据提交后台，保存的时候后台可能会返回数据不符合要求的错误，目前我的做法是下面代码，可以考虑增加上
 
App.post(url, values, function (r) {
            var obj = JSON.parse(r);
            if (obj.Code == 200) {
                view.hide();
                Ext.ComponentQuery.query(“dickmzdlist”)[0].controller.refresh();
                App.notify('消息', obj.Msg);
            } else {
                 var errors = obj.errors;
                 Ext.each(errors.errors,function (item) {
                     form.findField(item.field).markInvalid(item.message);
                 });
                App.alert('消息', obj.Msg);
            }
        });

**Comment by tengge1** [comment]
@ibmsoft 后台返回错误时，标记出表单哪个字段错误，我以后加上。感谢反馈。
