### ISSUE TITLE
原来老版本中的菜单管理是一个树形表格

### ISSUE THREAD

**Issue by ibmsoft** [tengge1/ExtApp#5]
原来老版本中的菜单管理是一个树形表格，个人感觉挺好的，新版本的没有这种实现了呢
老版本
![image](https://cloud.githubusercontent.com/assets/26042/25780415/435779c0-335a-11e7-865f-97245b1db705.png)

新版
![image](https://cloud.githubusercontent.com/assets/26042/25780427/812d9d06-335a-11e7-91b9-0bc804c67d91.png)

**Comment by tengge1** [comment]
右边会添加个菜单信息展示，点击一个菜单，显示这个菜单的信息。
