### ISSUE TITLE
表格数据会请求多次后台

### ISSUE THREAD

**Issue by ibmsoft** [tengge1/ExtApp#6]
init: function () {
        var view = this.getView();
        var store = Ext.create('store.dicbkzdlist');
        view.down('gridpanel').setStore(store);// 这里会请求一次
        view.down('pagingtoolbar').setStore(store);// 这里会请求一次
        store.reload();
        view.down('pagingtoolbar').moveFirst();
    },

**Comment by tengge1** [comment]
感谢反馈
