### ISSUE TITLE
与html页面同步传递数据

### ISSUE THREAD

**Issue by tengge1** [tengge1/ExtApp#9]
为了以后方便开发jsp和php版本，我们不打算将html页面更改为aspx页面。这带来了一个麻烦，html页面无法同步带来所需的数据（例如打开首页菜单无法立刻加载出来），往往需要借助Ajax再请求一次服务器，这使得用户体验非常不好。
我们想了一个办法，将数据库菜单、字典、配置等常用数据写入一个js文件，html将自动加载这个js文件，而不需要再使用Ajax请求后台，可以提高用户体验。

**Comment by ibmsoft** [comment]
目前我就是用的 java 版本的后台，支持这样处理。

**Comment by tengge1** [comment]
改为aspx页面了。
